### ISSUE TITLE
需要修复的 bug 和需要添加的 feat

### ISSUE THREAD

**Issue by YouXam** [byrdocs/byrdocs-cli#4]
- [x] upload 的时候保存提交历史记录到本地， init 的时候可以选择
- [x] upload 结束后的 init 询问修改为 InquirerPy
- [x] 统一 interrupt_handler 样式
- [x] 翻译全部指引成中文
- [x] 修改 ci 为 release 时触发
- [x] 修改 doc 的 course 字段为数组
- [x] 升级 pyyaml
- [x] 修改直接无参数输入 byrdocs 命令时的行为为进入菜单
- [x]  翻译 README，并优先推荐使用 pipx

**Comment by NoNormalCreeper** [comment]
- [ ] 修改直接无参数输入 `byrdocs` 命令时的行为为进入菜单

**Comment by NoNormalCreeper** [comment]
真的需要优先推荐 pipx 吗？我认为一是很多情况 pip 也能用，二是如果优先推荐 pipx 会多一步，而且在 Windows 上可能会很麻烦。

**Comment by YouXam** [comment]
> 真的需要优先推荐 pipx 吗？我认为一是很多情况 pip 也能用，二是如果优先推荐 pipx 会多一步，而且在 Windows 上可能会很麻烦。

那是否要根据不同系统决定？或者向用户说明不同？

**Comment by NoNormalCreeper** [comment]
> > 真的需要优先推荐 pipx 吗？我认为一是很多情况 pip 也能用，二是如果优先推荐 pipx 会多一步，而且在 Windows 上可能会很麻烦。
> 
> 那是否要根据不同系统决定？或者向用户说明不同？

我觉得说明一下不同吧。而且貌似不是系统的差异，是 Python 版本差异，我记得 PEP 一个草案中废弃了之前直接用 pip 直接安装 CLI 应用的方式，所以才安装不了。我觉得可以先简单说一下类似“pip 不行再换成 pipx”，以降低用户的操作和理解难度，下面额外补充上二者的差别也无妨。
