### ISSUE TITLE
支持brew安装

### ISSUE THREAD

**Issue by YouXam** [byrdocs/byrdocs-cli#6]

**Comment by NoNormalCreeper** [comment]
可以稍微详细解释下吗？



---Original---
From: ***@***.***&gt;
Sent at: 2024年12月6日(Fri) Early Morning1:01
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [byrdocs/byrdocs-cli] 支持brew安装 (Issue #6)




 
Assigned #6 to @NoNormalCreeper.

**Comment by NoNormalCreeper** [comment]
> It is possible to install some Python packages as formulae by using `brew install xyz`. We do not recommend using these formulae and instead recommend you install them with pip inside a virtualenv. These system-wide Homebrew Python formulae are often Homebrew-specific formulae that are useful as dependencies for other Homebrew formulae. It is not recommended to rely on them. 

https://docs.brew.sh/Homebrew-and-Python#pep-668-and-virtual-environments

**Comment by YouXam** [comment]
这应该是对于 python 模块的吧，但 cli 首先是一个命令行工具，其次才是一个 python 模块。用户也没有使用虚拟环境安装此模块并在代码中使用的需求。所以使用 brew 安装是为了使用该命令行程序，而不是使用该模块。

**Comment by liulifox233** [comment]
Done.
See [byrdocs/homebrew-byrdocs-cli](https://github.com/byrdocs/homebrew-byrdocs-cli).
